task2
js-tasks-ru/js-20230117_evgeniy396 pull request #2
Opened 2023-01-22 17:48 UTC by Evgeny20-04

2023-01-22 17:49 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-23 09:33 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return array.sort((a, b) => a.localeCompare(b, 'ru', { caseFirst: 'upper' }))
устраните дубликаты кода

2023-01-23 09:33 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return array.sort((a, b) => a.localeCompare(b, 'ru', { caseFirst: 'upper' })).reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-01-23 09:33 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +      delete newObj[key]
использовать `delete` в связке с объектом не рекомендуется, ведь копирование объекта `{...obj}` делает `shallow copy` или другими словами неглубокую копию, поэтому удаление может привести к весьма неожиданным последствиям

2023-01-23 09:34 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  Object.entries(obj).map(([key, value]) => {
здесь не нужен `map` - так как его следует применять когда есть необходимость получить новый массив с преобразованными эл-тами, здесь лучше подойдет `for...of` или `forEach`

2023-01-23 09:35 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2023-01-23 10:25 UTC, Evgeny20-04 commented on 02-javascript-data-types/2-pick/index.js
> +  Object.entries(obj).map(([key, value]) => {
Ок, с начала сделал через фор оф потом переделал через мап)))

2023-01-23 12:27 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-23 13:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-01-24 09:23 UTC, dosandk approved these changes
👍 good

2023-01-24 09:24 UTC, merged